# ----
# Site

title: Waktu Solat JSON API
description: Malaysia prayer times (waktu solat) JSON API. Data from JAKIM's E-Solat.
url: https://zaimramlan.github.io/waktu-solat-api/
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: APIs
    position: 2

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
